apiVersion: apps/v1
kind: Deployment
metadata:
  name: microblog-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: microblog-backend
  template:
    metadata:
      labels:
        app: microblog-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          ports:
            - containerPort: 3001
