apiVersion: v1
kind: Service
metadata:
  name: microblog-backend
spec:
  type: LoadBalancer
  loadBalancerIP: 172.201.33.227
  selector:
    app: microblog-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 3000
